---
- name: Check for NTP installation on Kubernetes worker nodes
  hosts: k8s_workers
  become: yes
  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Check if chrony or ntp is installed
      ansible.builtin.assert:
        that:
          - "'chrony' in ansible_facts.packages or 'ntp' in ansible_facts.packages"
        fail_msg: "Neither 'chrony' nor 'ntp' is installed on this node."
        success_msg: "NTP client (chrony or ntp) is installed."
