replicaCount: 3

image:
  repository: anandshivam44/node-app
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets:
  - name: dockerhub-secret
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}


service:
  type: LoadBalancer
  port: 3000


resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# MongoDB configuration
mongodb:
  enabled: true
  image:
    repository: mongo
    tag: "5.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
  persistence:
    enabled: false
    size: 8Gi
    storageClass: ""
  auth:
    enabled: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "512Mi"
      cpu: "500m"

# Application environment variables defaults
env:
  MONGODB_URL: "mongodb://node-app-release-mongodb:27017/database"
  NODE_ENV: "production"
  PORT: "3000"
